### PR TITLE
pr to merge milestone-1 into development

### PR DESCRIPTION
**Pull request by talhawaqar**
- In this milestone, I created a basic project structure according to the requirements.

### CODE REVIEW

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid.

Reason: 
- Please ensure all linting issues are checked and fixed.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Comment by mikenath223** [comment]
### STATUS: INVALID PR ❌

This PR has been marked as invalid once more.

Reason: 
- Please ensure all linting issues are checked and fixed **before requesting a new review**.

Feel free to contact me on slack(@michgolden) if you need further clarifications.

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Changes Requested 💀 

You have done a great job! I like your project. 

- You have a descriptive Readme
- Your Pull Request is nice. Good Job!
- You have deployed your website. Nice!!!
- You are using linters and no error is present. I am happy to see it. 
- Your code is clean.
**In short, I am very excited to see this project and proud of you. 👏** 

_There is always room to improve your code. Your project has met almost all the requirements but I would like to suggest some changes. I hope the next TSE who will review this project would be really impressed if you make those changes.  😄_ 

- [x] App should be deployed on Heroku(or other hosts like Netfliy, Firebase, etc) and the live link is included in the README file. 
- [ ] [Optional] Please make your Pull Request more descriptive. 

Don't get discouraged. There are some students who make more mistakes than you do. We are here to learn. Everyone from Micrverse is here to help you. 

**GOOD LUCK!**

In case of any question please reach out to me n slack @arslanbisharat. 📞 

**Best,
Arslan Bisharat** 🅰️

**Review by LamiaSristy — APPROVED** [review]
# Status: Approved. 🎉 🎉

Hello @talhawaqar, Fantastic work on this milestone. 

## The highlights: 
* The Live Demo is working.
##

Your milestone is now approved. Congratulations on your hard work. 🛠️ 

You can merge the branch now, good luck with your next milestone 🚀.

If you have any queries about this review, you know where to reach me!! @lamiasristy 🙋

Keep up the spirit always. Happy Coding 💻

**Pull request merged**
